#!/bin/sh
# Builds ClipboardCleaner.app, a double-clickable macOS app bundle, from the
# Swift package's release binary. Run from anywhere; paths are resolved
# relative to this script.
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
APP_NAME="Clipboard Cleaner"
BUNDLE_ID="com.local.clipboardcleaner"

cd "$ROOT_DIR"

TAG_VERSION="$(git describe --tags --exact-match --match 'v[0-9]*' 2>/dev/null || true)"
VERSION="${CLIPBOARD_CLEANER_VERSION:-${TAG_VERSION#v}}"
[ -n "$VERSION" ] || VERSION="0.0.0"
if ! printf '%s\n' "$VERSION" | grep -Eq '^[0-9]+(\.[0-9]+){0,2}$'; then
  echo "error: version must be numeric (for example v1.2.3 tag or CLIPBOARD_CLEANER_VERSION=1.2.3)" >&2
  exit 1
fi
BUILD_NUMBER="$(git rev-list --count HEAD 2>/dev/null || printf '1')"

echo "Building release binary..."
swift build -c release "$@"

BIN_DIR="$(swift build -c release --show-bin-path "$@")"
BIN_PATH="$BIN_DIR/ClipboardCleaner"
RESOURCE_BUNDLE="$BIN_DIR/ClipboardCleaner_ClipboardCleanerCore.bundle"
APP_DIR="$ROOT_DIR/build/$APP_NAME.app"
ICON_SOURCE="$ROOT_DIR/Assets/AppIcon.png"

rm -rf "$APP_DIR"
mkdir -p "$APP_DIR/Contents/MacOS"
mkdir -p "$APP_DIR/Contents/Resources"

cp "$BIN_PATH" "$APP_DIR/Contents/MacOS/ClipboardCleaner"

python3 "$SCRIPT_DIR/build_icon.py" \
  "$ICON_SOURCE" "$APP_DIR/Contents/Resources/AppIcon.icns"

# Everything must live under Contents/ for codesign to be able to seal the
# bundle and embed entitlements correctly (a resource bundle sitting
# outside Contents/ makes codesign refuse to produce a clean signature, and
# entitlements -- including the sandbox entitlement below -- silently don't
# get applied). So the rules JSON is placed directly in the standard
# Contents/Resources location; TrackingRuleCatalog falls back to
# Bundle.main's standard resource search to find it there when
# Bundle.module's SwiftPM-generated (dev-build-only) lookup doesn't apply.
RULES_JSON="$RESOURCE_BUNDLE/tracking-rules.json"
if [ ! -f "$RULES_JSON" ]; then
  # Newer SwiftPM/Xcode-style builds wrap package resources in a macOS
  # bundle layout instead of placing them directly at the bundle root.
  RULES_JSON="$RESOURCE_BUNDLE/Contents/Resources/tracking-rules.json"
fi
if [ -f "$RULES_JSON" ]; then
  cp "$RULES_JSON" "$APP_DIR/Contents/Resources/tracking-rules.json"
else
  echo "warning: expected rules file not found at $RULES_JSON" >&2
  exit 1
fi

cat > "$APP_DIR/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>$APP_NAME</string>
    <key>CFBundleDisplayName</key>
    <string>$APP_NAME</string>
    <key>CFBundleIdentifier</key>
    <string>$BUNDLE_ID</string>
    <key>CFBundleVersion</key>
    <string>$BUILD_NUMBER</string>
    <key>CFBundleShortVersionString</key>
    <string>$VERSION</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>CFBundleExecutable</key>
    <string>ClipboardCleaner</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>LSMinimumSystemVersion</key>
    <string>12.0</string>
    <key>LSUIElement</key>
    <true/>
    <key>NSHumanReadableCopyright</key>
    <string>Copyright © 2026 thetoadsage.</string>
</dict>
</plist>
PLIST

ENTITLEMENTS_PATH="$ROOT_DIR/build/ClipboardCleaner.entitlements"
cat > "$ENTITLEMENTS_PATH" <<ENTITLEMENTS
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
</dict>
</plist>
ENTITLEMENTS

# Files copied from Finder or generated by system image tools can carry
# extended attributes that codesign treats as unsealable resource-fork
# metadata. They are not application data and must not enter the bundle.
xattr -cr "$APP_DIR"

echo "Codesigning (ad hoc, sandboxed -- no network, no filesystem access outside the app's own container)..."
codesign --force --sign - --entitlements "$ENTITLEMENTS_PATH" "$APP_DIR"
# The workspace's file-provider layer may attach Finder metadata as soon as
# the .app becomes recognizable. Removing xattrs does not alter signed file
# contents and keeps subsequent strict verification deterministic.
xattr -cr "$APP_DIR"

echo "Built: $APP_DIR"
echo "Run it with: open \"$APP_DIR\""
